name: .NET Build, Test and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # ✅ 2. Setup .NET
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # ✅ 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # ✅ 4. Build
      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # ✅ 5. Publish
      - name: Publish project
        run: dotnet publish -c Release -o publish

      # ✅ 6. Inject appsettings.json from secrets
      - name: Create appsettings.json
        run: echo "${{ secrets.APPSETTINGS_JSON }}" > publish/appsettings.json

      - name: Create appsettings.Development.json
        run: echo "${{ secrets.APPSETTINGS_DEV_JSON }}" > publish/appsettings.Development.json

      # ✅ 7. Upload published files to EC2
      - name: Upload to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "publish/*"
          target: "/home/ubuntu/employee-app"

      # ✅ 8. SSH into EC2 and restart app
      - name: Run app on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /home/ubuntu/employee-app
            nohup dotnet EmployeeManagementSystem.dll > output.log 2>&1 &
