name: .NET Build, Test and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build EmployeeManagementSystem.csproj --configuration Release --no-restore

    - name: Publish project
      run: dotnet publish EmployeeManagementSystem.csproj -c Release -o publish

    - name: Write appsettings.json from secret
      run: |
        echo "${{ secrets.APPSETTINGS_JSON }}" > publish/appsettings.json
        echo "${{ secrets.APPSETTINGS_DEV_JSON }}" > publish/appsettings.Development.json

    - name: Upload published files to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: "publish/*"
        target: "/home/ubuntu/employee-app"

    - name: Restart app on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        command_timeout: 600
        script: |
          pkill -f EmployeeManagementSystem.dll || true
          cd /home/ubuntu/employee-app
          chmod +x EmployeeManagementSystem.dll
          (nohup dotnet EmployeeManagementSystem.dll > output.log 2>&1 </dev/null &)
          sleep 5
          echo "Application restarted successfully!"
          exit 0